image:
  file: .gitpod/.gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - name: Some init
    command: |
      sudo service mysql start
      sudo service php8.2-fpm start
      sudo service nginx start
      sudo mailhog </dev/null &>/dev/null & disown
      /bin/bash .gitpod/.init.sh

vscode:
  extensions:
    - eamodio.gitlens
    - felixfbecker.php-debug
    - sleistner.vscode-fileutils
    - streetsidesoftware.code-spell-checker
    - mrmlnc.vscode-duplicate
    - usernamehw.errorlens
    - RobertOstermann.inline-parameters-extended
    - zaaack.markdown-editor
    - neilbrayfield.php-docblocker
    - felixfbecker.php-pack
    - bmewburn.vscode-intelephense-client
    - StoilDobreff.php-resolver
    - ms-vscode.sublime-keybindings
    - sdras.night-owl
